### ISSUE TITLE
Optimistic Locks on multiple PDS - members leads to duplicated Job execution

### ISSUE THREAD

**Issue by Jeeppler** [Daimler/sechub#714] opened 2021-07-13 14:55 UTC
##### Note
- The origin problem is described here: the occurrence of optimistic lock entries.
- This was more or less only annoying
- After anlaysing the mentioned problem source it became clear that on a clusters this also did execute the JOBS multiple times (see comment below with title  "Critical bug detected")

## Problem

When PDS is using PostgreSQL as database, then Optimistic Lock problems occur. It does not matter if the cluster consists of only a single instance or more than one instance. The more instances the PDS cluster has, the more likely it becomes for the optimistic lock problem to occur.

### 1 PDS:

~~~
pds-gosec_1     | 2021-07-13 08:55:05.950  INFO 8 --- [0.0-8444-exec-2] c.d.s.pds.job.PDSFileUploadJobService    : Upload file sourcecode.zip for job b135466c-f2bd-434a-a900-10ffcb84c903 to storage
pds-gosec_1     | 2021-07-13 08:55:05.951  INFO 8 --- [0.0-8444-exec-2] c.d.s.s.s.spring.SharedVolumeJobStorage  : job:b135466c-f2bd-434a-a900-10ffcb84c903: storing sourcecode.zip in path pds/GOSEC_CLUSTER
pds-gosec_1     | 2021-07-13 08:55:05.953  INFO 8 --- [0.0-8444-exec-2] c.d.s.s.s.spring.SharedVolumeJobStorage  : job:b135466c-f2bd-434a-a900-10ffcb84c903: storing sourcecode.zip.checksum in path pds/GOSEC_CLUSTER
loadbalancer_1  | 172.20.0.1 - admin [13/Jul/2021:08:55:05 +0000] "POST /api/job/b135466c-f2bd-434a-a900-10ffcb84c903/upload/sourcecode.zip HTTP/1.1" 200 25 "-" "curl/7.58.0"
pds-gosec_1     | 2021-07-13 08:55:06.138  INFO 8 --- [0.0-8444-exec-1] c.d.s.pds.job.PDSJobTransactionService   : Mark job b135466c-f2bd-434a-a900-10ffcb84c903 as ready to start
loadbalancer_1  | 172.20.0.1 - admin [13/Jul/2021:08:55:06 +0000] "PUT /api/job/b135466c-f2bd-434a-a900-10ffcb84c903/mark-ready-to-start HTTP/1.1" 200 0 "-" "curl/7.58.0"
loadbalancer_1  | 172.20.0.1 - admin [13/Jul/2021:08:55:06 +0000] "GET /api/job/b135466c-f2bd-434a-a900-10ffcb84c903/status HTTP/1.1" 200 165 "-" "curl/7.58.0"
pds-gosec_1     | 2021-07-13 08:55:06.583  INFO 8 --- [pool-2-thread-1] c.d.s.p.execution.PDSExecutionCallable   : Prepare execution of job b135466c-f2bd-434a-a900-10ffcb84c903
pds-gosec_1     | 2021-07-13 08:55:06.601  INFO 8 --- [pool-2-thread-1] c.d.sechub.pds.job.PDSWorkspaceService   : Unzipped 2 files to /workspace/workspace/b135466c-f2bd-434a-a900-10ffcb84c903/upload/unzipped/sourcecode
pds-gosec_1     | 2021-07-13 08:55:06.602  INFO 8 --- [pool-2-thread-1] c.d.s.p.execution.PDSExecutionCallable   : Start launcher script for job b135466c-f2bd-434a-a900-10ffcb84c903
pds-gosec_1     | 2021-07-13 08:55:06.603 ERROR 8 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
pds-gosec_1     | 
pds-gosec_1     | org.springframework.orm.ObjectOptimisticLockingFailureException: Object of class [com.daimler.sechub.pds.job.PDSJob] with identifier [b135466c-f2bd-434a-a900-10ffcb84c903]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [com.daimler.sechub.pds.job.PDSJob#b135466c-f2bd-434a-a900-10ffcb84c903]
pds-gosec_1     | 	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:315)
pds-gosec_1     | 	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:233)
pds-gosec_1     | 	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:566)
…
pds-gosec_1     | Caused by: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [com.daimler.sechub.pds.job.PDSJob#b135466c-f2bd-434a-a900-10ffcb84c903]
~~~

The exception occurs after starting the execution script and before the job is done.

### 2 PDS

~~~
ds-gosec_1     | 2021-07-13 08:49:11.955  INFO 7 --- [0.0-8444-exec-1] c.d.s.pds.job.PDSFileUploadJobService    : Upload file sourcecode.zip for job 07411f09-ed0c-4d24-804d-b900f801e7a7 to storage
pds-gosec_1     | 2021-07-13 08:49:11.957  INFO 7 --- [0.0-8444-exec-1] c.d.s.s.s.spring.SharedVolumeJobStorage  : job:07411f09-ed0c-4d24-804d-b900f801e7a7: storing sourcecode.zip in path pds/GOSEC_CLUSTER
pds-gosec_1     | 2021-07-13 08:49:11.959  INFO 7 --- [0.0-8444-exec-1] c.d.s.s.s.spring.SharedVolumeJobStorage  : job:07411f09-ed0c-4d24-804d-b900f801e7a7: storing sourcecode.zip.checksum in path pds/GOSEC_CLUSTER
loadbalancer_1  | 172.20.0.1 - admin [13/Jul/2021:08:49:11 +0000] "POST /api/job/07411f09-ed0c-4d24-804d-b900f801e7a7/upload/sourcecode.zip HTTP/1.1" 200 0 "-" "curl/7.58.0"
pds-gosec_1     | 2021-07-13 08:49:12.162  INFO 7 --- [0.0-8444-exec-5] c.d.s.pds.job.PDSJobTransactionService   : Mark job 07411f09-ed0c-4d24-804d-b900f801e7a7 as ready to start
loadbalancer_1  | 172.20.0.1 - admin [13/Jul/2021:08:49:12 +0000] "PUT /api/job/07411f09-ed0c-4d24-804d-b900f801e7a7/mark-ready-to-start HTTP/1.1" 200 0 "-" "curl/7.58.0"
pds-gosec_2     | 2021-07-13 08:49:12.201  INFO 8 --- [pool-2-thread-2] c.d.s.p.execution.PDSExecutionCallable   : Prepare execution of job 07411f09-ed0c-4d24-804d-b900f801e7a7
pds-gosec_2     | 2021-07-13 08:49:12.213 ERROR 8 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
pds-gosec_2     | 
pds-gosec_2     | org.springframework.orm.ObjectOptimisticLockingFailureException: Object of class [com.daimler.sechub.pds.job.PDSJob] with identifier [07411f09-ed0c-4d24-804d-b900f801e7a7]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [com.daimler.sechub.pds.job.PDSJob#07411f09-ed0c-4d24-804d-b900f801e7a7]
…
pds-gosec_2     | Caused by: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [com.daimler.sechub.pds.job.PDSJob#07411f09-ed0c-4d24-804d-b900f801e7a7]
~~~

The issue occurs after starting the execution script and before the job is done in `pds-gosec_2`. `pds-gosec_1` handled the file upload.

### 3 PDS

~~~
pds-gosec_2     | 2021-07-13 08:27:32.122  INFO 10 --- [0.0-8444-exec-9] c.d.s.pds.job.PDSFileUploadJobService    : Upload file sourcecode.zip for job d40bba6b-f344-4446-846d-067e57df4ed6 to storage
pds-gosec_2     | 2021-07-13 08:27:32.123  INFO 10 --- [0.0-8444-exec-9] c.d.s.s.s.spring.SharedVolumeJobStorage  : job:d40bba6b-f344-4446-846d-067e57df4ed6: storing sourcecode.zip in path pds/GOSEC_CLUSTER
pds-gosec_2     | 2021-07-13 08:27:32.123  INFO 10 --- [0.0-8444-exec-9] c.d.s.s.s.spring.SharedVolumeJobStorage  : job:d40bba6b-f344-4446-846d-067e57df4ed6: storing sourcecode.zip.checksum in path pds/GOSEC_CLUSTER
loadbalancer_1  | 172.20.0.1 - admin [13/Jul/2021:08:27:32 +0000] "POST /api/job/d40bba6b-f344-4446-846d-067e57df4ed6/upload/sourcecode.zip HTTP/1.1" 200 25 "-" "curl/7.58.0"
pds-gosec_2     | 2021-07-13 08:27:32.301  INFO 10 --- [0.0-8444-exec-8] c.d.s.pds.job.PDSJobTransactionService   : Mark job d40bba6b-f344-4446-846d-067e57df4ed6 as ready to start
loadbalancer_1  | 172.20.0.1 - admin [13/Jul/2021:08:27:32 +0000] "PUT /api/job/d40bba6b-f344-4446-846d-067e57df4ed6/mark-ready-to-start HTTP/1.1" 200 0 "-" "curl/7.58.0"
loadbalancer_1  | 172.20.0.1 - admin [13/Jul/2021:08:27:32 +0000] "GET /api/job/d40bba6b-f344-4446-846d-067e57df4ed6/status HTTP/1.1" 200 165 "-" "curl/7.58.0"
pds-gosec_1     | 2021-07-13 08:27:32.612  INFO 8 --- [pool-2-thread-3] c.d.s.p.execution.PDSExecutionCallable   : Prepare execution of job d40bba6b-f344-4446-846d-067e57df4ed6
pds-gosec_3     | 2021-07-13 08:27:32.618  INFO 7 --- [pool-2-thread-4] c.d.s.p.execution.PDSExecutionCallable   : Prepare execution of job d40bba6b-f344-4446-846d-067e57df4ed6
pds-gosec_1     | 2021-07-13 08:27:32.627  INFO 8 --- [pool-2-thread-3] c.d.s.p.execution.PDSExecutionCallable   : Had optimistic lock problem on update for job d40bba6b-f344-4446-846d-067e57df4ed6 - do retry nr.1
pds-gosec_1     | 2021-07-13 08:27:32.642  INFO 8 --- [pool-2-thread-3] c.d.s.p.execution.PDSExecutionCallable   : Had optimistic lock problem on update for job d40bba6b-f344-4446-846d-067e57df4ed6 - do retry nr.2
pds-gosec_3     | 2021-07-13 08:27:32.640 ERROR 7 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task
pds-gosec_3     | 
pds-gosec_3     | org.springframework.orm.ObjectOptimisticLockingFailureException: Object of class [com.daimler.sechub.pds.job.PDSJob] with identifier [d40bba6b-f344-4446-846d-067e57df4ed6]: optimistic locking failed; nested exception is org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [com.daimler.sechub.pds.job.PDSJob#d40bba6b-f344-4446-846d-067e57df4ed6]
…
pds-gosec_3     | Caused by: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [com.daimler.sechub.pds.job.PDSJob#d40bba6b-f344-4446-846d-067e57df4ed6]
~~~

In this case, both `pds-gosec_1` and `pds-gosec_3` prepare for the job execution. `pds-gosec_1` reports it had an optimistic lock problem, but `pds-gosec_3` throws the actual exception. `pds-gosec_2` handled the file upload.

## Wanted

The PDS should scale up to 100s of instances without having optimistic lock problems.

[optimistic_lock_exception.txt](https://github.com/Daimler/sechub/files/6809885/optimistic_lock_exception.txt)

**Comment by de-jcup** [comment] 2021-07-13 19:18
With #701 LocalTestPostgreSQLStarter is introduced (inside developer tools). With this simple java application we can easily start a local postgres testcontainer instance.

So it is also very easy to start automated a postgres instance + use it at integration test PDS server when executing integration tests!  So we can create an integration test, which initially fails and then start fixing the problem.

**Comment by de-jcup** [comment] 2021-07-13 19:29
`PDSBatchTriggerService.triggerExecutionOfNextJob()` seems to be the problem:

```java
    @Transactional //3a
    public void triggerExecutionOfNextJob() {
           //... more
           PDSJob pdsJob = nextJob.get();
           pdsJob.setState(PDSJobStatusState.QUEUED); // 1

            executionService.addToExecutionQueueAsynchron(pdsJob.getUUID()); //2
     }//3b
```
Problem: 
// 1: changes job inside this thread, so this transaction, but transaction is not closed, so not committed
// 2 : triggers asynchronous execution inside queue - if fast enough queue will change job
// 3b : closes transaction and does commit - when queue execution fast enough, we got a optimistic lock exception

**Comment by de-jcup** [comment] 2021-07-16 08:25
There exists a test script in gosec which reproduces former exceptions easily:

https://github.com/Daimler/sechub/blob/feature-671-new-pds-version/sechub-pds-examples/gosec/70-test.sh

**Comment by de-jcup** [comment] 2021-07-19 13:07
The mentioned problem situation

> // 1: changes job inside this thread, but transaction (3a) is not closed, so not committed
> // 2 : triggers asynchronous execution inside queue with other transaction - if fast enough queue will change job
> // 3b : closes transaction and does commit with outdated PDSJob (it has been changed inside other transaction in 2 ) - when queue execution fast enough, we got a optimistic lock exception

is only a potential problem inside same JVM.

Running multiple cluster members, we have another situation:

Member1 reads at same time as Member 2 and updates the job

**Comment by de-jcup** [comment] 2021-07-19 13:09
## CRITICAL bug detected:

using https://github.com/Daimler/sechub/blob/feature-671-new-pds-version/sechub-pds-examples/gosec/
and calling
```
./50-start-multiple-docker-compose.sh 
```
followed by a 
```
./70-test.sh
```
inside another terminal, I got:


```
pds-gosec_2     | 2021-07-19 10:46:51.579  INFO 8 --- [pool-2-thread-2] c.d.s.p.execution.PDSExecutionCallable   : Had optimistic lock problem on update for job fef457d2-a91f-4bdf-9840-19f94ff3c497 - do retry nr.2
pds-gosec_1     | 2021-07-19 10:46:51.594  INFO 8 --- [pool-2-thread-1] c.d.sechub.pds.job.PDSWorkspaceService   : Unzipped 2 files to /workspace/workspace/fef457d2-a91f-4bdf-9840-19f94ff3c497/upload/unzipped/sourcecode
pds-gosec_1     | 2021-07-19 10:46:51.597  INFO 8 --- [pool-2-thread-1] c.d.s.p.execution.PDSExecutionCallable   : Start launcher script for job fef457d2-a91f-4bdf-9840-19f94ff3c497
pds-gosec_2     | 2021-07-19 10:46:51.599  INFO 8 --- [pool-2-thread-2] c.d.sechub.pds.job.PDSWorkspaceService   : Unzipped 2 files to /workspace/workspace/fef457d2-a91f-4bdf-9840-19f94ff3c497/upload/unzipped/sourcecode
pds-gosec_2     | 2021-07-19 10:46:51.601  INFO 8 --- [pool-2-thread-2] c.d.s.p.execution.PDSExecutionCallable   : Start launcher script for job fef457d2-a91f-4bdf-9840-19f94ff3c497

```
So I got SAME JOB running on DIFFERENT cluster members!

This may never happen. Must be fixed!

**Comment by de-jcup** [comment] 2021-07-19 14:39
To create some payload I just called:
```
for i in {0..100..1}; do ./70-test.sh /home/myUser/Downloads/files.zip; done
```

**Comment by de-jcup** [comment] 2021-07-19 15:33
After last commit the problem of double executed Jobs no longer exists.
Also race condition handling at cluster job execution was improved : When a job is already fetched by another cluster member (version increment by fetch leads to an optimistic lock exception) the cluster member makes a log entry about "Next job was already handled ...", waits a random time (50-3000 millis) and then does a instant retry. 

The former test was done sequential, after some tries on a cluster with 3 members I had 0-2 info messages.

So I improved the test scenario and did it parallel:
```
./50-start-multiple-docker-compose.sh 3 >> pds-cluster.log 2>&1
```
Then execute former command in parallel:
```
for i in {0..100..1}; do ./70-test.sh /home/albert/Downloads/files.zip & done
```
This does a massive scan.  

After this inspection is possible by 
`less pds-cluster.log |grep -c "Next job was already handled by another cluster member"`


Result: after last commit the logs contain only an information marker about the retry (which is okay)
no duplicated executions. The retry information is okay (IMHO).

**Comment by de-jcup** [comment] 2021-07-20 06:33
NOTE: The used solution doing an OPTIMISTIC_FORCE_INCREMENT by jpa/spring is better than the alternative, which would be to lock the complete table...

**Closed** 2021-07-21 15:03 UTC
Labels: bug, pds
