### ISSUE TITLE
admin-ui: request new api token for existing user "Email address is not valid"

### ISSUE THREAD

**Issue by manu-ki** [Daimler/sechub#449] opened 2020-11-13 12:31 UTC
We got a request by another user that the Admin UI action "Request API token for existing user" 
produces error "Email adress is not valid'" when mailadress contains "_" 
_(e.g. this_is_an_example@example.com)_

How to reproduce?
- create an user with such kind of email address (works...)
- request a new api token

Should be verified and fixed

---
Manuela Kirchner manuela.kirchner@daimler.com, Daimler TSS GmbH, imprint

**Comment by de-jcup** [comment] 2021-01-13 11:28
Was not able to reproduce problem. But added some missing tests. Tested also manually over admin UI and worked as well. So closing this issue

**Closed** 2021-01-13 11:29 UTC
Labels: bug, invalid, server
