### ISSUE TITLE
Admin shall be able to deactivate projects

### ISSUE THREAD

**Issue by de-jcup** [Daimler/sechub#95] opened 2019-11-27 08:36 UTC
## Use cases

"As an administrator I want to deactivate a project and also to reactivate it"

So we must create:
- UC_ADMIN_DEACTIVATE_PROJECT
- UC_ADMIN_ACTIVATE_PROJECT

## Restrictions
When a project is deactivated
- a new scan is not possible, HTTP 403: Forbidden will be sent
- running jobs are still running
- already scheduled jobs will be scheduled
- user are still able to check status for a job in their project
- user can still download their former reports

When project is reactivated
- new scans are possible again

## Addtional
- Changes shall be notified to project owner, users and admins

---
<sup>Albert Tregnaghi <albert.tregnaghi@daimler.com>, Daimler TSS GmbH, [imprint](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sup>

**Comment by sven-dmlr** [comment] 2020-08-07 09:49
Is a duplicate of #192

**Closed** 2020-10-22 05:11 UTC
Labels: documentation, duplicate, enhancement, operation, server, usecase
