### ISSUE TITLE
Project description must be changeable and shall appear in project detail JSON

### ISSUE THREAD

**Issue by sven-dmlr** [Daimler/sechub#558] opened 2021-02-18 08:30 UTC
## Situation
- Currently we cannot change a description for a project
- The project description does also not appear inside the project detail JSON 
  (see https://daimler.github.io/sechub/latest/sechub-restapi.html#section-usecase-UC_021)

## Wanted
As an administrator I want to
- change the description for a project
- see description when I fetch project details

## Solution
- New REST endpoint to update description
- Enhance details 

related to: #332

**Comment by de-jcup** [comment] 2021-02-18 13:20
Duplicate of https://github.com/Daimler/sechub/issues/97

**Comment by sven-dmlr** [comment] 2021-02-18 13:26
Thanks for the hint.
It's only partly duplicate.

**Comment by de-jcup** [comment] 2021-02-18 13:43
@sven-dmlr  I updated the issue so it contains only the comment part. So we can work parallel on #97 and this one

**Closed** 2021-05-03 09:26 UTC
Labels: administration, api
